services:
  mlapp:
    container_name: mlapp
    image: francescoxx/mlapp
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000